# Generated by Django 4.2.7 on 2023-11-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_brand_product_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_category',
            new_name='ProductCategory',
        ),
    ]
