# Generated by Django 4.2.7 on 2023-11-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
