# Generated by Django 4.2.7 on 2023-11-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='field',
        ),
    ]
