# Generated by Django 4.2.2 on 2023-11-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('seller', 'seller'), ('admin', 'admin'), ('customer', 'customer')], max_length=10),
        ),
    ]
