# Generated by Django 4.2.7 on 2024-01-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_otp_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
