# Generated by Django 4.2.7 on 2023-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Order Placed', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='total_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
