# Generated by Django 4.2.7 on 2023-12-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(default='order placed', max_length=255),
        ),
    ]
