# Generated by Django 4.2.7 on 2023-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='status',
            field=models.CharField(default='waiting for confirmation', max_length=255),
        ),
    ]
